apiVersion: v1
kind: Secret
metadata:
  name:  pullkey
  namespace: system
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJkb2NrZXJodWIucWluZ2Nsb3VkLmNvbSI6IHsKCQkJImF1dGgiOiAiYldGbmFXTnpiMjVuT25OdmJtY3hNak54ZVE9PSIKCQl9LAoJCSJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CgkJCSJhdXRoIjogImJXRm5hV056YjI1bk9uTnZibWN4TWpOa2IyTnJaWEk9IgoJCX0KCX0sCgkiSHR0cEhlYWRlcnMiOiB7CgkJIlVzZXItQWdlbnQiOiAiRG9ja2VyLUNsaWVudC8xOC4wMy4xLWNlIChsaW51eCkiCgl9Cn0K