{{ if .Values.customImage.enable }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: openelb-images
  namespace: {{ template "openelb.namespace" . }}
data:
  {{ if (ne .Values.customImage.forwardImage "") }}
  forward-image: {{ .Values.customImage.forwardImage }}
  {{ end }}
  
  {{ if (ne .Values.customImage.proxyImage "") }}
  proxy-image:  {{ .Values.customImage.proxyImage }}
  {{ end }}
{{ end }}