kind: Service
apiVersion: v1
metadata:
  name:  mylbapp
  annotations:
    lb.kubesphere.io/v1alpha1: porter
spec:
  externalIPs:
  - 139.198.121.228
  selector:
    app:  mylbapp
  type:  LoadBalancer 
  ports:
  - name:  http
    port:  8088
    targetPort:  80

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mylbapp
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: mylbapp
    spec:
      containers:
      - name: name
        image: nginx:alpine
        ports:
        - containerPort: 80