# Default values for OpenELB.
# This is a YAML-formatted file.
global:
  imageRegistry: docker.io # registry.cn-beijing.aliyuncs.com   docker.io
  tag: # "v1.0.0"
  imagePullSecrets: []

admission:
  image:
    # registry: docker.io
    repository: kubespheredev/kube-webhook-certgen
    tag: v1.1.1
    pullPolicy: IfNotPresent

controller:
  monitorEnable: false
  monitorPort: 50052
  webhookPort: 443
  image:
    # registry: docker.io
    repository: rykren/openelb-controller
    tag: test
    pullPolicy: IfNotPresent
  resources:
    limits:
      cpu: 500m
      memory: 500Mi
    requests:
      cpu: 100m
      memory: 100Mi
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: app
                operator: In
                values:
                  - openelb-controller
          topologyKey: "kubernetes.io/hostname"
  tolerations:
    - key: CriticalAddonsOnly
      operator: Exists
    - effect: NoSchedule
      key: node-role.kubernetes.io/master
  nodeSelector:
    kubernetes.io/os: linux
      
speaker:
  enable: true
  vip: false
  layer2: true
  memberlistSecret: "" # openelb-speakers
  apiHosts: ":50051"
  monitorEnable: false
  monitorPort: 50052
  image:
    # registry: docker.io
    repository: rykren/openelb-speaker
    tag: test
    pullPolicy: IfNotPresent
  resources:
    limits:
      cpu: 500m
      memory: 500Mi
    requests:
      cpu: 100m
      memory: 100Mi
  tolerations:
    - key: CriticalAddonsOnly
      operator: Exists
    - effect: NoSchedule
      key: node-role.kubernetes.io/master
  nodeSelector:
    kubernetes.io/os: linux

customImage:
  enable: true
  vipImage: ""      # "kubesphere/kube-keepalived-vip:0.35"
  forwardImage: ""  # kubesphere/openelb-forward:master
  proxyImage: ""    # kubesphere/openelb-proxy:master
