
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.4.0
  creationTimestamp: null
  name: bgpconfs.network.kubesphere.io
spec:
  group: network.kubesphere.io
  names:
    kind: BgpConf
    listKind: BgpConfList
    plural: bgpconfs
    singular: bgpconf
  scope: Cluster
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: BgpConf is the Schema for the bgpconfs API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: struct for container bgp:config. Configuration parameters
              relating to the global BGP router.
            properties:
              as:
                description: original -> bgp:as bgp:as's original type is inet:as-number.
                  Local autonomous system number of the router.  Uses the 32-bit as-number
                  type from the model in RFC 6991.
                format: int32
                type: integer
              port:
                description: original -> gobgp:port
                format: int32
                maximum: 65535
                minimum: 1
                type: integer
              routerID:
                description: original -> bgp:router-id bgp:router-id's original type
                  is inet:ipv4-address. Router id of the router, expressed as an 32-bit
                  value, IPv4 address.
                pattern: ^([0-9]{1,3}\.){3}[0-9]{1,3}$
                type: string
            required:
            - as
            - port
            - routerID
            type: object
          status:
            description: BgpConfStatus defines the observed state of BgpConf
            type: object
        type: object
    served: true
    storage: false
  - name: v1alpha2
    schema:
      openAPIV3Schema:
        description: BgpConf is the Schema for the bgpconfs API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: Configuration parameters relating to the global BGP router.
            properties:
              as:
                format: int32
                type: integer
              asPerRack:
                additionalProperties:
                  format: int32
                  type: integer
                type: object
              families:
                items:
                  format: int32
                  type: integer
                type: array
              gracefulRestart:
                properties:
                  deferralTime:
                    format: int32
                    type: integer
                  enabled:
                    type: boolean
                  helperOnly:
                    type: boolean
                  localRestarting:
                    type: boolean
                  longlivedEnabled:
                    type: boolean
                  mode:
                    type: string
                  notificationEnabled:
                    type: boolean
                  peerRestartTime:
                    format: int32
                    type: integer
                  peerRestarting:
                    type: boolean
                  restartTime:
                    format: int32
                    type: integer
                  staleRoutesTime:
                    format: int32
                    type: integer
                type: object
              listenAddresses:
                items:
                  type: string
                type: array
              listenPort:
                format: int32
                type: integer
              policy:
                type: string
              routerId:
                type: string
              useMultiplePaths:
                type: boolean
            type: object
          status:
            description: BgpConfStatus defines the observed state of BgpConf
            properties:
              nodesConfStatus:
                additionalProperties:
                  properties:
                    as:
                      format: int32
                      type: integer
                    routerId:
                      type: string
                  type: object
                type: object
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
